-- TradeOS TimescaleDB Schema
-- Run once at setup:  psql -d tradeos -f schema.sql
-- All timestamps stored as TIMESTAMPTZ in IST (Asia/Kolkata).

CREATE EXTENSION IF NOT EXISTS timescaledb CASCADE;

SET timezone = 'Asia/Kolkata';

-- ==========================================================================
-- TABLE 1: ticks
-- Raw validated tick data. TimescaleDB hypertable partitioned by received_at.
-- Chunk interval: 1 day.  Retention: 90 days.
-- ==========================================================================

CREATE TABLE IF NOT EXISTS ticks (
    id                 BIGSERIAL,
    instrument_token   INTEGER        NOT NULL,
    symbol             TEXT           NOT NULL,
    last_price         NUMERIC(12,2)  NOT NULL,
    volume_traded      BIGINT,
    oi                 BIGINT,
    bid_price          NUMERIC(12,2),
    ask_price          NUMERIC(12,2),
    exchange_timestamp TIMESTAMPTZ    NOT NULL,
    received_at        TIMESTAMPTZ    NOT NULL DEFAULT NOW(),
    session_date       DATE           NOT NULL
);

SELECT create_hypertable(
    'ticks', 'received_at',
    chunk_time_interval => INTERVAL '1 day',
    if_not_exists       => TRUE
);

CREATE INDEX IF NOT EXISTS idx_ticks_token_received
    ON ticks (instrument_token, received_at DESC);

SELECT add_retention_policy('ticks', INTERVAL '90 days', if_not_exists => TRUE);


-- ==========================================================================
-- TABLE 2: candles_15m
-- 15-minute OHLCV + VWAP candles. Schema defined now; populated by Strategy
-- Engine (Phase 1).
-- ==========================================================================

CREATE TABLE IF NOT EXISTS candles_15m (
    instrument_token   INTEGER        NOT NULL,
    symbol             TEXT           NOT NULL,
    open               NUMERIC(12,2)  NOT NULL,
    high               NUMERIC(12,2)  NOT NULL,
    low                NUMERIC(12,2)  NOT NULL,
    close              NUMERIC(12,2)  NOT NULL,
    volume             BIGINT         NOT NULL,
    vwap               NUMERIC(12,2),
    candle_time        TIMESTAMPTZ    NOT NULL,
    session_date       DATE           NOT NULL,
    PRIMARY KEY (instrument_token, candle_time)
);


-- ==========================================================================
-- TABLE 3: signals
-- Every signal generated by S1 with full indicator snapshot.
-- Source of truth for the Observer dashboard "why" view.
-- ==========================================================================

CREATE TABLE IF NOT EXISTS signals (
    id                 BIGSERIAL      PRIMARY KEY,
    session_date       DATE           NOT NULL,
    symbol             TEXT           NOT NULL,
    instrument_token   INTEGER        NOT NULL,
    direction          TEXT           NOT NULL
                           CHECK (direction IN ('LONG', 'SHORT')),
    signal_time        TIMESTAMPTZ    NOT NULL,
    candle_time        TIMESTAMPTZ    NOT NULL,
    -- Indicator snapshot at signal time (non-negotiable for dashboard)
    ema9               NUMERIC(12,4)  NOT NULL,
    ema21              NUMERIC(12,4)  NOT NULL,
    rsi                NUMERIC(6,2)   NOT NULL,
    vwap               NUMERIC(12,2)  NOT NULL,
    volume_ratio       NUMERIC(6,2)   NOT NULL,
    -- Theoretical prices
    theoretical_entry  NUMERIC(12,2)  NOT NULL,
    stop_loss          NUMERIC(12,2)  NOT NULL,
    target             NUMERIC(12,2)  NOT NULL,
    -- Outcome (filled later by order_monitor)
    order_id           TEXT,
    status             TEXT           NOT NULL DEFAULT 'PENDING'
                           CHECK (status IN (
                               'PENDING', 'FILLED', 'REJECTED',
                               'KILL_SWITCHED', 'IGNORED'
                           )),
    reject_reason      TEXT
);

CREATE INDEX IF NOT EXISTS idx_signals_session_symbol
    ON signals (session_date, symbol);


-- ==========================================================================
-- TABLE 4: trades
-- Every completed trade with full entry/exit detail and P&L.
-- One row per closed position. Written when position closes.
-- ==========================================================================

CREATE TABLE IF NOT EXISTS trades (
    id                 BIGSERIAL      PRIMARY KEY,
    session_date       DATE           NOT NULL,
    symbol             TEXT           NOT NULL,
    direction          TEXT           NOT NULL,
    signal_id          BIGINT         REFERENCES signals(id),
    -- Entry
    entry_order_id     TEXT           NOT NULL,
    entry_time         TIMESTAMPTZ    NOT NULL,
    actual_entry       NUMERIC(12,2)  NOT NULL,
    theoretical_entry  NUMERIC(12,2)  NOT NULL,
    entry_slippage     NUMERIC(12,2),
    qty                INTEGER        NOT NULL,
    -- Exit
    exit_order_id      TEXT,
    exit_time          TIMESTAMPTZ,
    actual_exit        NUMERIC(12,2),
    exit_reason        TEXT
                           CHECK (exit_reason IS NULL OR exit_reason IN (
                               'TARGET_HIT', 'STOP_HIT', 'HARD_EXIT_1500',
                               'KILL_SWITCH', 'MANUAL', 'PARTIAL_FILL_CLOSE'
                           )),
    -- P&L (calculated on close, stored for fast dashboard queries)
    gross_pnl          NUMERIC(12,2),
    charges            NUMERIC(10,2),
    net_pnl            NUMERIC(12,2),
    pnl_pct            NUMERIC(8,4)
);

CREATE INDEX IF NOT EXISTS idx_trades_session_symbol
    ON trades (session_date, symbol);


-- ==========================================================================
-- TABLE 5: system_events
-- System health audit trail for the health dashboard.
-- ==========================================================================

CREATE TABLE IF NOT EXISTS system_events (
    id                 BIGSERIAL      PRIMARY KEY,
    session_date       DATE           NOT NULL,
    event_time         TIMESTAMPTZ    NOT NULL DEFAULT NOW(),
    event_type         TEXT           NOT NULL,
    level              TEXT           CHECK (level IN ('INFO', 'WARNING', 'CRITICAL')),
    detail             JSONB,
    kill_switch_level  INTEGER
);

CREATE INDEX IF NOT EXISTS idx_system_events_session_type
    ON system_events (session_date, event_type);
CREATE INDEX IF NOT EXISTS idx_system_events_time
    ON system_events (event_time DESC);


-- ==========================================================================
-- TABLE 6: backtest_candles
-- Historical OHLCV candles downloaded from KiteConnect for backtesting.
-- ==========================================================================

CREATE TABLE IF NOT EXISTS backtest_candles (
    instrument_token   INTEGER        NOT NULL,
    symbol             TEXT           NOT NULL,
    interval           TEXT           NOT NULL,
    open               NUMERIC(12,2)  NOT NULL,
    high               NUMERIC(12,2)  NOT NULL,
    low                NUMERIC(12,2)  NOT NULL,
    close              NUMERIC(12,2)  NOT NULL,
    volume             BIGINT         NOT NULL,
    oi                 BIGINT,
    candle_time        TIMESTAMPTZ    NOT NULL,
    session_date       DATE           NOT NULL,

    PRIMARY KEY (instrument_token, interval, candle_time),

    CONSTRAINT chk_interval CHECK (
        interval IN ('5min', '15min', '30min', '1hour', 'day')
    )
);

CREATE INDEX IF NOT EXISTS idx_bt_candles_symbol_interval_time
    ON backtest_candles (symbol, interval, candle_time);

CREATE INDEX IF NOT EXISTS idx_bt_candles_session_interval
    ON backtest_candles (session_date, interval);


-- ==========================================================================
-- TABLE 7: backtest_metadata
-- Download progress tracking per symbol + interval.
-- ==========================================================================

CREATE TABLE IF NOT EXISTS backtest_metadata (
    id                 SERIAL         PRIMARY KEY,
    symbol             TEXT           NOT NULL,
    instrument_token   INTEGER        NOT NULL,
    interval           TEXT           NOT NULL,
    date_from          DATE           NOT NULL,
    date_to            DATE           NOT NULL,
    rows_downloaded    INTEGER,
    downloaded_at      TIMESTAMPTZ    DEFAULT NOW(),

    CONSTRAINT uq_bt_metadata_symbol_interval UNIQUE (symbol, interval)
);


-- ==========================================================================
-- TABLE 8: backtest_runs
-- Summary results of each backtest execution.
-- ==========================================================================

CREATE TABLE IF NOT EXISTS backtest_runs (
    id                 SERIAL         PRIMARY KEY,
    strategy           TEXT           NOT NULL,
    params             JSONB          NOT NULL,
    exit_mode          TEXT,
    date_from          DATE           NOT NULL,
    date_to            DATE           NOT NULL,
    total_trades       INTEGER,
    win_rate           NUMERIC(6,2),
    gross_pnl          NUMERIC(14,2),
    total_charges      NUMERIC(14,2),
    net_pnl            NUMERIC(14,2),
    max_drawdown       NUMERIC(14,2),
    max_drawdown_pct   NUMERIC(8,4),
    sharpe_ratio       NUMERIC(8,4),
    profit_factor      NUMERIC(8,4),
    avg_win            NUMERIC(12,2),
    avg_loss           NUMERIC(12,2),
    expectancy         NUMERIC(12,2),
    created_at         TIMESTAMPTZ    DEFAULT NOW()
);


-- ==========================================================================
-- TABLE 9: backtest_trades
-- Detailed trade log per backtest run.
-- ==========================================================================

CREATE TABLE IF NOT EXISTS backtest_trades (
    id                 SERIAL         PRIMARY KEY,
    run_id             INTEGER        NOT NULL REFERENCES backtest_runs(id),
    symbol             TEXT           NOT NULL,
    direction          TEXT           NOT NULL,
    entry_time         TIMESTAMPTZ,
    exit_time          TIMESTAMPTZ,
    entry_price        NUMERIC(12,2),
    exit_price         NUMERIC(12,2),
    exit_reason        TEXT,
    qty                INTEGER        NOT NULL,
    gross_pnl          NUMERIC(12,2),
    charges            NUMERIC(10,2),
    net_pnl            NUMERIC(12,2),
    regime             TEXT
);

CREATE INDEX IF NOT EXISTS idx_bt_trades_run_symbol
    ON backtest_trades (run_id, symbol);
